#spring.application.name=eventservice
spring:
    application:
          name: eventservice
          server:
              port: 8081

    datasource:
          url: jdbc:mysql://localhost:3306/event
          username: root
          password: Aayukris@2002
          driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
          hibernate:
              ddl-auto: update
          show-sql: true
    properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQLDialect
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
